name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.asciidoc'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.asciidoc'

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        php-version: [ '7.2', '7.3', '7.4', '8.0', '8.1' ]
        dockerfile: [ 'Dockerfile', 'Dockerfile.alpine' ]
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: PHP_VERSION=${{ matrix.php-version }} DOCKERFILE=${{ matrix.dockerfile }} make -f .ci/Makefile prepare
      - name: Build
        run: PHP_VERSION=${{ matrix.php-version }} DOCKERFILE=${{ matrix.dockerfile }} make -f .ci/Makefile build
      - name: Check
        run: PHP_VERSION=${{ matrix.php-version }} DOCKERFILE=${{ matrix.dockerfile }} make -f .ci/Makefile static-check-unit-test
      - name: Package
        run: PHP_VERSION=${{ matrix.php-version }} DOCKERFILE=${{ matrix.dockerfile }} make -f .ci/Makefile generate-for-package
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ matrix.php-version }}
          path: src/ext/modules/*.so

  package:
    runs-on: ubuntu-latest
    needs: [test]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          path: src/ext/modules/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: src/ext/modules/
      - name: Package
        run: make -C packaging package
      - name: Info
        run: make -C packaging info
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-package
          path: build/packages/*

  test-package:
    runs-on: ubuntu-latest
    needs: [ package ]
    timeout-minutes: 30
    strategy:
      matrix:
        php-version: [ '7.2', '7.3', '7.4', '8.0', '8.1' ]
        type: [ 'apk', 'deb', 'rpm' ]
        kind: [ 'cli', 'http' ]
        test: [ 'lifecycle' ]
        group: [ 'no_ext_svc', 'with_ext_svc' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: artifact-package
          path: build/packages/
      - name: Prepare
        run: make -C packaging prepare-${{ matrix.type }} PHP_VERSION=${{ matrix.php-version }}
      - name: Lifecycle
        run: make -C packaging ${{ matrix.type }}-${{ matrix.test }}-testing PHP_VERSION=${{ matrix.php-version }}
        env:
          ELASTIC_APM_PHP_TESTS_MATRIX_ROW: ${{ matrix.php-version }},${{ matrix.type }},${{ matrix.test }},${{ matrix.kind }},${{ matrix.group }}
