name: test

on:
  pull_request:
    paths-ignore:
      - "**/*.asciidoc"
      - "**/*.md"
      - "**/*.png"
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.asciidoc"
      - "**/*.md"
      - "**/*.png"

permissions:
  contents: read

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      php-versions: ${{ steps.generate-matrix.outputs.php-versions }}
      php-versions-limits: ${{ steps.generate-matrix.outputs.php-versions-limits }}
      lifecycle-package: ${{ steps.generate-matrix.outputs.lifecycle-type }}
      lifecycle-group: ${{ steps.generate-matrix.outputs.lifecycle-group }}
      lifecycle-subgroup: ${{ steps.generate-matrix.outputs.lifecycle-subgroup }}
      lifecycle-testing: ${{ steps.generate-matrix.outputs.lifecycle-testing }}
      lifecycle-apache-package: ${{ steps.generate-matrix.outputs.lifecycle-apache-package }}
      lifecycle-apache-group: ${{ steps.generate-matrix.outputs.lifecycle-apache-group }}
      lifecycle-apache-subgroup: ${{ steps.generate-matrix.outputs.lifecycle-apache-subgroup }}
      lifecycle-apache-testing: ${{ steps.generate-matrix.outputs.lifecycle-apache-testing }}
      lifecycle-debug-package: ${{ steps.generate-matrix.outputs.lifecycle-debug-package }}
      lifecycle-debug-group: ${{ steps.generate-matrix.outputs.lifecycle-debug-group }}
      lifecycle-debug-subgroup: ${{ steps.generate-matrix.outputs.lifecycle-debug-subgroup }}
      lifecycle-debug-testing: ${{ steps.generate-matrix.outputs.lifecycle-debug-testing }}
    steps:
      - uses: actions/checkout@v3
      - id: generate-matrix
        run: .ci/generate-github-matrix.sh

  test:
    name: static-checks-unit-tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - prepare-matrix
    strategy:
      fail-fast: false
      matrix:
        php-version: ${{ fromJSON(needs.prepare-matrix.outputs.php-versions) }}
        dockerfile:
          - "Dockerfile"
          - "Dockerfile.alpine"
    env:
      PHP_VERSION: ${{ matrix.php-version }}
      DOCKERFILE: ${{ matrix.dockerfile }}
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: make -f .ci/Makefile prepare
      - name: Build
        run: make -f .ci/Makefile build
      - name: Static Check / Unit tests
        run: make -f .ci/Makefile static-check-unit-test
      - name: Build parts for packages
        run: make -f .ci/Makefile generate-for-package
      - uses: actions/upload-artifact@v3
        with:
          name: package-parts
          path: src/ext/modules/*.so
      - if: success() || failure()
        name: Prepare Upload
        run: >-
          find build
          -name "*junit.xml"
          -exec bash -c 'mv {} "build/${PHP_VERSION}-${DOCKERFILE}-$(basename {})"'
          \;
      - if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/*junit.xml
          if-no-files-found: error

  build-packages:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: package-parts
          path: src/ext/modules
      - name: package
        run: make -C packaging package
      - name: package info
        run: make -C packaging info
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: |
            build/packages/*
            !build/packages/**/*.sha512

  test-packages-lifecycle-apache:
    timeout-minutes: 120
    needs:
      - build-packages
      - test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        php-version: ${{ fromJSON(needs.prepare-matrix.outputs.php-versions) }}
        package: ${{ fromJSON(needs.prepare-matrix.outputs.lifecycle-apache-package) }}
        group: ${{ fromJSON(needs.prepare-matrix.outputs.lifecycle-apache-group) }}
        subgroup: ${{ fromJSON(needs.prepare-matrix.outputs.lifecycle-apache-subgroup) }}
        testing: ${{ fromJSON(needs.prepare-matrix.outputs.lifecycle-apache-testing) }}
    env:
      ELASTIC_APM_PHP_TESTS_MATRIX_ROW: "${{ matrix.php-version }},${{ matrix.package }},${{ matrix.testing }},${{ matrix.subgroup }},${{ matrix.group }}"
      PHP_VERSION: ${{ matrix.php-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/test-packages
        with:
          package: ${{ matrix.package }}
          testing: ${{ matrix.testing }}

  test-packages-lifecycle:
    timeout-minutes: 120
    needs:
      - build-packages
      - test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        php-version: ${{ fromJSON(needs.prepare-matrix.outputs.php-versions) }}
        package: ${{ fromJSON(needs.prepare-matrix.outputs.lifecycle-package) }}
        group: ${{ fromJSON(needs.prepare-matrix.outputs.lifecycle-group) }}
        subgroup: ${{ fromJSON(needs.prepare-matrix.outputs.lifecycle-subgroup) }}
        testing: ${{ fromJSON(needs.prepare-matrix.outputs.lifecycle-testing) }}
    env:
      ELASTIC_APM_PHP_TESTS_MATRIX_ROW: "${{ matrix.php-version }},${{ matrix.package }},${{ matrix.testing }},${{ matrix.subgroup }},${{ matrix.group }}"
      PHP_VERSION: ${{ matrix.php-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/test-packages
        with:
            package-type: ${{ matrix.package }}
            testing-type: ${{ matrix.testing }}

  test-packages-lifecycle-debug:
    timeout-minutes: 120
    needs:
      - build-packages
      - test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        php-version: ${{ fromJSON(needs.prepare-matrix.outputs.php-versions-limits) }}
        package: ${{ fromJSON(needs.prepare-matrix.outputs.lifecycle-debug-package) }}
        group: ${{ fromJSON(needs.prepare-matrix.outputs.lifecycle-debug-group) }}
        subgroup: ${{ fromJSON(needs.prepare-matrix.outputs.lifecycle-debug-subgroup) }}
        testing: ${{ fromJSON(needs.prepare-matrix.outputs.lifecycle-debug-testing) }}
    env:
      ELASTIC_APM_PHP_TESTS_MATRIX_ROW: "${{ matrix.php-version }},${{ matrix.package }},${{ matrix.testing }},${{ matrix.subgroup }},${{ matrix.group }},agent_syslog_level=DEBUG"
      PHP_VERSION: ${{ matrix.php-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/test-packages
        with:
          package-type: ${{ matrix.package }}
          testing-type: ${{ matrix.testing }}
